on: [push]
name: Build and Test
jobs:
  check:
    name: pddl_rs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Run cargo build
        run: cargo build --release
      - name: Run cargo test
        run: cargo test --release --all-features